#!/usr/bin/env python3
"""
sync-constants.py
Reads constants.yaml and propagates values to every service.

Usage:
    python scripts/sync-constants.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# Minimal YAML parser (no external deps needed for our flat/nested structure)
# ---------------------------------------------------------------------------

def parse_yaml(text: str) -> dict:
    result = {}
    current_section = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if line.startswith("  ") and current_section is not None:
            k, _, v = line.strip().partition(":")
            result[current_section][k.strip()] = v.strip().strip('"')
        else:
            k, _, v = line.partition(":")
            k = k.strip()
            v = v.strip().strip('"')
            if v:
                result[k] = v
            else:
                current_section = k
                result[k] = {}
    return result


# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------

_HEADER_LINES = [
    "Code generated by scripts/sync-constants.py — DO NOT EDIT manually.",
    "Run  python scripts/sync-constants.py  after editing constants.yaml.",
]

def _comment(lines, prefix="// "):
    return "\n".join(prefix + l for l in lines)


def write_go(c: dict):
    path = ROOT / "internal/config/constants.go"
    urls = c["urls"]
    content = f"""\
package config

{_comment(_HEADER_LINES)}

const (
\tVersion = "{c['version']}"

\tURLWebApp       = "{urls['web_app']}"
\tURLAPI          = "{urls['api']}"
\tURLDocs         = "{urls['docs']}"
\tURLStatus       = "{urls['status']}"
\tURLGitHub       = "{urls['github']}"
\tURLDiscordInvite = "{urls['discord_invite']}"
\tURLContact      = "{urls['contact']}"

\tEmailNoreply = "{c['email']['noreply']}"
)
"""
    path.write_text(content)
    print(f"  ✓  {path.relative_to(ROOT)}")


def write_ts(c: dict):
    path = ROOT / "web/src/config/constants.ts"
    urls = c["urls"]
    content = f"""\
{_comment(_HEADER_LINES)}

export const VERSION = "{c['version']}";

export const URLS = {{
  webApp:        "{urls['web_app']}",
  api:           "{urls['api']}",
  docs:          "{urls['docs']}",
  status:        "{urls['status']}",
  github:        "{urls['github']}",
  discordInvite: "{urls['discord_invite']}",
  contact:       "{urls['contact']}",
}} as const;
"""
    path.write_text(content)
    print(f"  ✓  {path.relative_to(ROOT)}")


def write_kotlin(c: dict):
    path = ROOT / "mobile/android/app/src/main/kotlin/com/chronos/reminder/core/AppConstants.kt"
    urls = c["urls"]
    content = f"""\
package com.chronos.reminder.core

{_comment(_HEADER_LINES)}

object AppConstants {{

    const val VERSION = "{c['version']}"

    object Urls {{
        const val WEB_APP        = "{urls['web_app']}"
        const val API            = "{urls['api']}"
        const val DOCS           = "{urls['docs']}"
        const val STATUS         = "{urls['status']}"
        const val GITHUB         = "{urls['github']}"
        const val DISCORD_INVITE = "{urls['discord_invite']}"
        const val CONTACT        = "{urls['contact']}"
    }}
}}
"""
    path.write_text(content)
    print(f"  ✓  {path.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# File patchers
# ---------------------------------------------------------------------------

def patch(path: Path, pattern: str, replacement: str, label: str):
    text = path.read_text()
    new_text, n = re.subn(pattern, replacement, text)
    if n == 0:
        print(f"  ⚠  {label}: pattern not found in {path.relative_to(ROOT)}", file=sys.stderr)
        return
    path.write_text(new_text)
    print(f"  ✓  {path.relative_to(ROOT)}  ({label})")


def patch_gradle(c: dict):
    path = ROOT / "mobile/android/app/build.gradle.kts"
    patch(path, r'versionCode\s*=\s*\d+', f'versionCode = {c["android_version_code"]}', "versionCode")
    patch(path, r'versionName\s*=\s*"[^"]*"', f'versionName = "{c["version"]}"', "versionName")


def patch_ci_api(c: dict):
    path = ROOT / ".github/workflows/build-container.yml"
    image = c["docker"]["api_image"]
    ver = c["version"]
    patch(path, rf'tags:\s*{re.escape(image)}:[^\s]+', f'tags: {image}:{ver}', "Docker tag")


def patch_ci_web(c: dict):
    path = ROOT / ".github/workflows/build-web-container.yml"
    patch(path, r'type=raw,value=[^\s]+', f'type=raw,value={c["version"]}', "Docker tag")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    yaml_path = ROOT / "constants.yaml"
    if not yaml_path.exists():
        print(f"ERROR: {yaml_path} not found", file=sys.stderr)
        sys.exit(1)

    c = parse_yaml(yaml_path.read_text())
    print(f"\nSyncing constants  (version {c['version']})\n")

    print("Generating constants files:")
    write_go(c)
    write_ts(c)
    write_kotlin(c)

    print("\nPatching versioned files:")
    patch_gradle(c)
    patch_ci_api(c)
    patch_ci_web(c)

    print("\nDone. Commit constants.yaml and all generated/patched files together.\n")


if __name__ == "__main__":
    main()
